site_name: LeetCode Solutions
repo_url: https://github.com/s-sreedhar/Leetcode
site_author: Sreedhar Goud

nav:
  - Home: index.md
  - About Me: about.md
  - License: license.md
theme:
  name: material
  # custom_dir: overrides
  logo: logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - announce.dismiss
    - header.autohide
    - toc.integrate
    - toc.follow
    - navigation.footer
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: lime
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: lime
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

docs_dir: docs
extra:
  logo: logo.png
  include_markdown:
    base_path: ".."
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/s_sreedhargoud
    - icon: fontawesome/brands/github
      link: https://github.com/s-sreedhar
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/ssreedhargoud
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/s_sreedhargoud

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 - 2025 <a href="https://github.com/s-sreedhar"  target="_blank" rel="noopener">Sreedhar Goud</a> <br>
  <a href="#__consent">Change cookie settings</a>
