name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main # Change this if your default branch is different
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Use the latest compatible Python version

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-material-extensions
          pip install pymdown-extensions
          pip install mkdocs-include-markdown-plugin
          pip install mkdocs-simple-hooks

      - name: Build and Deploy MkDocs
        run: |
          mkdocs build --strict
          mkdocs gh-deploy --force
